function renderSubs(){
  const active = subscriptions.filter(subscription => ['pending','active','past_due','paused'].includes(subscription.status));
  const mrr = active.reduce((total, subscription) => {
    const plan = subscription.plans; if (!plan) return total;
    const divisor = plan.billing_interval === 'yearly' ? 12 : plan.billing_interval === 'quarterly' ? 3 : 1;
    return total + Number(plan.price || 0) / divisor;
  }, 0);
  document.getElementById('subs-stats').innerHTML = `<div class="stat-card"><div class="stat-icon">✅</div><div class="stat-n">${active.length}</div><div class="stat-label">Suscripciones vigentes</div></div><div class="stat-card"><div class="stat-icon">💰</div><div class="stat-n">$${mrr.toLocaleString('es-AR')}</div><div class="stat-label">MRR estimado</div></div><div class="stat-card"><div class="stat-icon">📊</div><div class="stat-n">${subscriptions.length}</div><div class="stat-label">Suscripciones totales</div></div>`;
  document.getElementById('subs-tbody').innerHTML = subscriptions.map(subscription => { const plan = subscription.plans || {}; const user = subscription.users || {}; return `<tr><td class="td-name">${user.name || '—'} ${user.apellido || ''}<br><span style="font-size:11px;color:var(--ink3)">${user.email || ''}</span></td><td><span class="badge badge-blue">${plan.name || '—'}</span></td><td><span class="badge ${subscription.status === 'active' ? 'badge-green' : 'badge-amber'}">${subscription.status}</span></td><td style="font-size:12px">${subscription.started_at ? new Date(subscription.started_at).toLocaleDateString('es-AR') : '—'}</td><td style="font-size:12px">${subscription.current_period_end ? new Date(subscription.current_period_end).toLocaleDateString('es-AR') : '—'}</td><td style="font-size:13px;font-weight:500">${plan.price ? `${plan.currency || 'ARS'} ${Number(plan.price).toLocaleString('es-AR')}` : '—'}</td></tr>`; }).join('') || '<tr><td colspan="6" style="text-align:center;padding:2rem">Sin suscripciones</td></tr>';
}
